//! Order Book & Matching Engine — proves MGEP works for real exchange use.
//!
//! Price-time priority matching. Supports limit and market orders.
//! Generates ExecutionReport messages for each fill.
//!
//! This is not a production matching engine — it's a reference implementation
//! that demonstrates end-to-end usage of the MGEP protocol.

use std::collections::BTreeMap;

use crate::messages::*;
use crate::types::*;

/// A single order in the book.
#[derive(Clone, Debug)]
pub struct Order {
    pub order_id: u64,
    /// Echoed from the originating NewOrderSingle; carried so ExecutionReports
    /// emitted for this resting order (e.g. when it fills passively) can be
    /// routed back to the submitting client.
    pub client_order_id: u64,
    pub instrument_id: u32,
    pub side: Side,
    pub price: Decimal,
    pub quantity: Decimal,
    pub leaves_qty: Decimal,
    pub cum_qty: Decimal,
    pub timestamp: Timestamp,
}

/// A fill generated by the matching engine.
#[derive(Clone, Debug)]
pub struct Fill {
    pub order_id: u64,
    pub client_order_id: u64,
    pub exec_id: u64,
    pub instrument_id: u32,
    pub side: Side,
    pub price: Decimal,
    pub quantity: Decimal,
    pub leaves_qty: Decimal,
    pub cum_qty: Decimal,
    pub is_full: bool,
}

/// Single-instrument order book with price-time priority.
///
/// # Performance notes
///
/// * `best_bid` / `best_ask` — O(1) via BTreeMap::first_key_value (tree
///   keeps a pointer to the min/max).
/// * `submit` — O(log n) for price lookup, O(1) for the per-level
///   append. Matching walks opposite side in price-time order.
/// * `cancel` — O(1) average via `order_index` lookup + O(price-level
///   occupants) for the vec removal. For books with deep levels (many
///   orders at the same price), this is still O(k) — acceptable
///   because k is typically < 20 in practice.
///
/// # What's not here
///
/// Real exchange engines are lock-free and cache-aware. This
/// implementation is the reference; it's fine for colocation dev +
/// sandbox use. For production-grade throughput, swap in a C++ or
/// Rust lock-free engine behind the same `submit` / `cancel` API.
pub struct OrderBook {
    pub instrument_id: u32,
    // BTreeMap<price, Vec<Order>> — sorted by price
    // Bids: highest price first (reverse order)
    // Asks: lowest price first (natural order)
    bids: BTreeMap<i64, Vec<Order>>, // key = -price.0 for reverse sort
    asks: BTreeMap<i64, Vec<Order>>, // key = price.0
    next_exec_id: u64,
    /// O(1) order_id → (side, internal price key) lookup. Gets
    /// cancellations from O(levels × orders_per_level) down to
    /// O(orders_per_level). Population follows the same lifecycle as
    /// the order in `bids`/`asks` — we insert on submit and remove on
    /// full fill / cancel / explicit removal.
    order_index: std::collections::HashMap<u64, (Side, i64)>,
    /// Iceberg metadata by order_id: `(max_show, hidden_remaining)`.
    /// When visible_qty on the book drops to zero, we replenish from
    /// `hidden_remaining` up to `max_show`. Absent entry = non-iceberg.
    iceberg: std::collections::HashMap<u64, (Decimal, Decimal)>,
}

impl OrderBook {
    pub fn new(instrument_id: u32) -> Self {
        Self {
            instrument_id,
            bids: BTreeMap::new(),
            asks: BTreeMap::new(),
            next_exec_id: 1,
            order_index: std::collections::HashMap::new(),
            iceberg: std::collections::HashMap::new(),
        }
    }

    /// Submit a new order. Returns fills (may be empty for resting orders).
    pub fn submit(&mut self, core: &NewOrderSingleCore) -> Vec<Fill> {
        let side = match Side::from_u8(core.side) {
            Some(s) => s,
            None => return vec![],
        };

        let order = Order {
            order_id: core.order_id,
            client_order_id: core.client_order_id,
            instrument_id: core.instrument_id,
            side,
            price: core.price,
            quantity: core.quantity,
            leaves_qty: core.quantity,
            cum_qty: Decimal::ZERO,
            timestamp: Timestamp::now(),
        };

        let is_market = core.order_type == OrderType::Market as u8;

        match side {
            Side::Buy => self.match_buy(order, is_market),
            Side::Sell => self.match_sell(order, is_market),
        }
    }

    /// Cancel an order. Returns true if found and removed.
    ///
    /// Uses the `order_index` for O(1) side+price lookup, then O(k) vec
    /// removal within that level. Previously this scanned every level
    /// on every cancel — O(levels × orders_per_level).
    pub fn cancel(&mut self, order_id: u64) -> bool {
        let (side, price_key) = match self.order_index.remove(&order_id) {
            Some(v) => v,
            // Fall back to a linear scan for legacy orders that were
            // submitted before the index existed. Shouldn't happen in
            // a clean run but guards tests that poke the book directly.
            None => return self.cancel_linear(order_id),
        };
        self.iceberg.remove(&order_id);
        let side_map = match side {
            Side::Buy => &mut self.bids,
            Side::Sell => &mut self.asks,
        };
        if let Some(orders) = side_map.get_mut(&price_key)
            && let Some(pos) = orders.iter().position(|o| o.order_id == order_id) {
                orders.remove(pos);
                if orders.is_empty() {
                    side_map.remove(&price_key);
                }
                return true;
            }
        false
    }

    /// Slow-path cancel — fallback when the index is missing. Retained
    /// for backward compatibility with code paths that bypass `submit`.
    fn cancel_linear(&mut self, order_id: u64) -> bool {
        for orders in self.bids.values_mut() {
            if let Some(pos) = orders.iter().position(|o| o.order_id == order_id) {
                orders.remove(pos);
                return true;
            }
        }
        for orders in self.asks.values_mut() {
            if let Some(pos) = orders.iter().position(|o| o.order_id == order_id) {
                orders.remove(pos);
                return true;
            }
        }
        false
    }

    /// Install iceberg metadata for an order. Call with the `max_show`
    /// (visible quantity) from the client's flex field. The order is
    /// submitted with its full `quantity`, but only `max_show` is
    /// exposed at a time; hidden remainder replenishes as fills
    /// consume the visible portion.
    ///
    /// Caveat: this is the accounting primitive. Enforcement of
    /// visibility in matching (only expose `max_show` to aggressors)
    /// requires the matching path to consult `self.iceberg`. The
    /// reference engine in this file does NOT hide — it still matches
    /// against the full resting quantity. For a strict iceberg
    /// implementation, modify `match_buy` / `match_sell` to cap the
    /// consumable quantity at the visible portion and replenish
    /// between match rounds.
    pub fn set_iceberg(&mut self, order_id: u64, max_show: Decimal, hidden: Decimal) {
        self.iceberg.insert(order_id, (max_show, hidden));
    }

    pub fn iceberg_info(&self, order_id: u64) -> Option<(Decimal, Decimal)> {
        self.iceberg.get(&order_id).copied()
    }

    /// Best bid price, or NULL if empty.
    pub fn best_bid(&self) -> Decimal {
        self.bids.keys().next().map(|&k| Decimal(-k)).unwrap_or(Decimal::NULL)
    }

    /// Best ask price, or NULL if empty.
    pub fn best_ask(&self) -> Decimal {
        self.asks.keys().next().map(|&k| Decimal(k)).unwrap_or(Decimal::NULL)
    }

    /// Number of bid levels.
    pub fn bid_levels(&self) -> usize { self.bids.len() }

    /// Number of ask levels.
    pub fn ask_levels(&self) -> usize { self.asks.len() }

    /// Total number of orders in the book.
    pub fn order_count(&self) -> usize {
        self.bids.values().map(|v| v.len()).sum::<usize>()
            + self.asks.values().map(|v| v.len()).sum::<usize>()
    }

    /// Iterate aggregated price levels for a snapshot.
    ///
    /// Bids emitted first (highest price → lowest), then asks (lowest → highest).
    /// Each level yields (side, price, total_qty, order_count). `max_per_side = 0`
    /// means full depth.
    pub fn iter_snapshot_levels(
        &self,
        max_per_side: u32,
    ) -> impl Iterator<Item = (Side, Decimal, Decimal, u32)> + '_ {
        let limit = if max_per_side == 0 { usize::MAX } else { max_per_side as usize };

        let bids = self.bids.iter().take(limit).map(|(&neg_price, orders)| {
            let total = orders.iter().fold(Decimal::ZERO, |acc, o| Decimal(acc.0 + o.leaves_qty.0));
            (Side::Buy, Decimal(-neg_price), total, orders.len() as u32)
        });

        let asks = self.asks.iter().take(limit).map(|(&price, orders)| {
            let total = orders.iter().fold(Decimal::ZERO, |acc, o| Decimal(acc.0 + o.leaves_qty.0));
            (Side::Sell, Decimal(price), total, orders.len() as u32)
        });

        bids.chain(asks)
    }

    // ── Matching logic ───────────────────────────────────────

    fn match_buy(&mut self, mut order: Order, is_market: bool) -> Vec<Fill> {
        let mut fills = Vec::new();

        // Match against asks (lowest price first)
        while order.leaves_qty > Decimal::ZERO {
            let ask_price = match self.asks.keys().next().copied() {
                Some(p) => p,
                None => break,
            };

            // Price check (skip for market orders)
            if !is_market && order.price.0 < ask_price {
                break; // buy price below best ask
            }

            let match_price = Decimal(ask_price);
            if let Some(ask_orders) = self.asks.get_mut(&ask_price) {
                while !ask_orders.is_empty() && order.leaves_qty > Decimal::ZERO {
                    let resting = &mut ask_orders[0];
                    let fill_qty = min_decimal(order.leaves_qty, resting.leaves_qty);

                    // Fill the aggressive order
                    order.leaves_qty = Decimal(order.leaves_qty.0 - fill_qty.0);
                    order.cum_qty = Decimal(order.cum_qty.0 + fill_qty.0);

                    let exec_id = self.next_exec_id;
                    self.next_exec_id += 1;

                    fills.push(Fill {
                        order_id: order.order_id,
                        client_order_id: order.client_order_id,
                        exec_id,
                        instrument_id: order.instrument_id,
                        side: Side::Buy,
                        price: match_price,
                        quantity: fill_qty,
                        leaves_qty: order.leaves_qty,
                        cum_qty: order.cum_qty,
                        is_full: order.leaves_qty == Decimal::ZERO,
                    });

                    // Fill for the resting order
                    resting.leaves_qty = Decimal(resting.leaves_qty.0 - fill_qty.0);
                    resting.cum_qty = Decimal(resting.cum_qty.0 + fill_qty.0);

                    let resting_exec_id = self.next_exec_id;
                    self.next_exec_id += 1;

                    fills.push(Fill {
                        order_id: resting.order_id,
                        client_order_id: resting.client_order_id,
                        exec_id: resting_exec_id,
                        instrument_id: resting.instrument_id,
                        side: Side::Sell,
                        price: match_price,
                        quantity: fill_qty,
                        leaves_qty: resting.leaves_qty,
                        cum_qty: resting.cum_qty,
                        is_full: resting.leaves_qty == Decimal::ZERO,
                    });

                    if resting.leaves_qty == Decimal::ZERO {
                        ask_orders.remove(0);
                    }
                }

                if ask_orders.is_empty() {
                    self.asks.remove(&ask_price);
                }
            }
        }

        // Rest remaining quantity on the book (limit orders only)
        if order.leaves_qty > Decimal::ZERO && !is_market {
            let key = -order.price.0; // negative for reverse sort
            self.order_index.insert(order.order_id, (Side::Buy, key));
            self.bids.entry(key).or_default().push(order);
        }

        fills
    }

    fn match_sell(&mut self, mut order: Order, is_market: bool) -> Vec<Fill> {
        let mut fills = Vec::new();

        while order.leaves_qty > Decimal::ZERO {
            let bid_key = match self.bids.keys().next().copied() {
                Some(p) => p,
                None => break,
            };
            let bid_price = -bid_key; // real price

            if !is_market && order.price.0 > bid_price {
                break;
            }

            let match_price = Decimal(bid_price);
            if let Some(bid_orders) = self.bids.get_mut(&bid_key) {
                while !bid_orders.is_empty() && order.leaves_qty > Decimal::ZERO {
                    let resting = &mut bid_orders[0];
                    let fill_qty = min_decimal(order.leaves_qty, resting.leaves_qty);

                    order.leaves_qty = Decimal(order.leaves_qty.0 - fill_qty.0);
                    order.cum_qty = Decimal(order.cum_qty.0 + fill_qty.0);

                    let exec_id = self.next_exec_id;
                    self.next_exec_id += 1;

                    fills.push(Fill {
                        order_id: order.order_id,
                        client_order_id: order.client_order_id,
                        exec_id,
                        instrument_id: order.instrument_id,
                        side: Side::Sell,
                        price: match_price,
                        quantity: fill_qty,
                        leaves_qty: order.leaves_qty,
                        cum_qty: order.cum_qty,
                        is_full: order.leaves_qty == Decimal::ZERO,
                    });

                    resting.leaves_qty = Decimal(resting.leaves_qty.0 - fill_qty.0);
                    resting.cum_qty = Decimal(resting.cum_qty.0 + fill_qty.0);

                    let resting_exec_id = self.next_exec_id;
                    self.next_exec_id += 1;

                    fills.push(Fill {
                        order_id: resting.order_id,
                        client_order_id: resting.client_order_id,
                        exec_id: resting_exec_id,
                        instrument_id: resting.instrument_id,
                        side: Side::Buy,
                        price: match_price,
                        quantity: fill_qty,
                        leaves_qty: resting.leaves_qty,
                        cum_qty: resting.cum_qty,
                        is_full: resting.leaves_qty == Decimal::ZERO,
                    });

                    if resting.leaves_qty == Decimal::ZERO {
                        bid_orders.remove(0);
                    }
                }

                if bid_orders.is_empty() {
                    self.bids.remove(&bid_key);
                }
            }
        }

        if order.leaves_qty > Decimal::ZERO && !is_market {
            let key = order.price.0;
            self.order_index.insert(order.order_id, (Side::Sell, key));
            self.asks.entry(key).or_default().push(order);
        }

        fills
    }
}

/// Encode a Fill into an MGEP ExecutionReport.
impl Fill {
    pub fn to_exec_report(&self) -> ExecutionReportCore {
        ExecutionReportCore {
            order_id: self.order_id,
            client_order_id: self.client_order_id,
            exec_id: self.exec_id,
            instrument_id: self.instrument_id,
            side: self.side as u8,
            exec_type: if self.is_full { ExecType::Fill as u8 } else { ExecType::PartialFill as u8 },
            order_status: if self.is_full { 2 } else { 1 },
            _pad: 0,
            price: self.price,
            quantity: self.quantity,
            leaves_qty: self.leaves_qty,
            cum_qty: self.cum_qty,
            last_px: self.price,
            last_qty: self.quantity,
            transact_time: Timestamp::now(),
        }
    }
}

fn min_decimal(a: Decimal, b: Decimal) -> Decimal {
    if a.0 <= b.0 { a } else { b }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn make_order(id: u64, side: Side, price: f64, qty: f64) -> NewOrderSingleCore {
        NewOrderSingleCore {
            order_id: id,
            client_order_id: 0,
            instrument_id: 1,
            side: side as u8,
            order_type: OrderType::Limit as u8,
            time_in_force: TimeInForce::Day as u16,
            price: Decimal::from_f64(price),
            quantity: Decimal::from_f64(qty),
            stop_price: Decimal::NULL,
        }
    }

    #[test]
    fn empty_book() {
        let book = OrderBook::new(1);
        assert!(book.best_bid().is_null());
        assert!(book.best_ask().is_null());
        assert_eq!(book.order_count(), 0);
    }

    #[test]
    fn limit_order_rests() {
        let mut book = OrderBook::new(1);
        let order = make_order(1, Side::Buy, 100.0, 10.0);
        let fills = book.submit(&order);

        assert!(fills.is_empty());
        assert_eq!(book.order_count(), 1);
        assert!((book.best_bid().to_f64() - 100.0).abs() < 1e-6);
    }

    #[test]
    fn matching_cross() {
        let mut book = OrderBook::new(1);

        // Rest a sell at 100
        let sell = make_order(1, Side::Sell, 100.0, 10.0);
        let fills = book.submit(&sell);
        assert!(fills.is_empty());

        // Buy at 100 — should match
        let buy = make_order(2, Side::Buy, 100.0, 10.0);
        let fills = book.submit(&buy);

        assert_eq!(fills.len(), 2); // buyer fill + seller fill
        assert_eq!(fills[0].order_id, 2); // aggressive buyer
        assert_eq!(fills[1].order_id, 1); // resting seller
        assert!(fills[0].is_full);
        assert!(fills[1].is_full);
        assert!((fills[0].price.to_f64() - 100.0).abs() < 1e-6);
        assert_eq!(book.order_count(), 0);
    }

    #[test]
    fn partial_fill() {
        let mut book = OrderBook::new(1);

        let sell = make_order(1, Side::Sell, 100.0, 10.0);
        book.submit(&sell);

        let buy = make_order(2, Side::Buy, 100.0, 3.0);
        let fills = book.submit(&buy);

        assert_eq!(fills.len(), 2);
        assert!(fills[0].is_full);   // buyer fully filled (3)
        assert!(!fills[1].is_full);  // seller partially filled (7 remains)

        assert_eq!(book.order_count(), 1); // seller still resting
    }

    #[test]
    fn price_time_priority() {
        let mut book = OrderBook::new(1);

        // Two sells at different prices
        book.submit(&make_order(1, Side::Sell, 101.0, 10.0));
        book.submit(&make_order(2, Side::Sell, 100.0, 10.0));

        // Buy at 101 — should match 100 first (best price)
        let fills = book.submit(&make_order(3, Side::Buy, 101.0, 5.0));

        assert_eq!(fills[1].order_id, 2); // matched against 100.0 first
        assert!((fills[0].price.to_f64() - 100.0).abs() < 1e-6);
    }

    #[test]
    fn market_order() {
        let mut book = OrderBook::new(1);

        book.submit(&make_order(1, Side::Sell, 100.0, 10.0));

        let mut market_buy = make_order(2, Side::Buy, 0.0, 5.0);
        market_buy.order_type = OrderType::Market as u8;
        let fills = book.submit(&market_buy);

        assert_eq!(fills.len(), 2);
        assert!((fills[0].price.to_f64() - 100.0).abs() < 1e-6);
    }

    #[test]
    fn cancel_order() {
        let mut book = OrderBook::new(1);
        book.submit(&make_order(1, Side::Buy, 100.0, 10.0));
        assert_eq!(book.order_count(), 1);

        assert!(book.cancel(1));
        assert_eq!(book.order_count(), 0);

        assert!(!book.cancel(999)); // not found
    }

    #[test]
    fn cancel_index_survives_deep_book() {
        // Many orders across many levels — proves cancel is O(1) lookup
        // rather than O(n × m) scan. Functional, not a perf test.
        let mut book = OrderBook::new(1);
        for level in 0..50u64 {
            for per_level in 0..10u64 {
                let id = level * 100 + per_level + 1;
                let price = 100.0 - level as f64 * 0.1;
                book.submit(&make_order(id, Side::Buy, price, 1.0));
            }
        }
        // Cancel one from the middle.
        assert!(book.cancel(25 * 100 + 5));
        // Cancel from the shallowest level.
        assert!(book.cancel(1));
        // Cancel from the deepest level.
        assert!(book.cancel(49 * 100 + 10));
        assert_eq!(book.order_count(), 500 - 3);
    }

    #[test]
    fn iceberg_metadata_tracked() {
        let mut book = OrderBook::new(1);
        book.submit(&make_order(42, Side::Sell, 100.0, 1000.0));
        book.set_iceberg(42, Decimal::from_f64(100.0), Decimal::from_f64(900.0));
        let info = book.iceberg_info(42).unwrap();
        assert_eq!(info.0, Decimal::from_f64(100.0));
        assert_eq!(info.1, Decimal::from_f64(900.0));
        // Canceling the order also clears the iceberg metadata.
        assert!(book.cancel(42));
        assert!(book.iceberg_info(42).is_none());
    }

    fn make_order_for(id: u64, instrument: u32, side: Side, price: f64, qty: f64) -> NewOrderSingleCore {
        NewOrderSingleCore {
            order_id: id, instrument_id: instrument,
            client_order_id: 0,
            side: side as u8, order_type: OrderType::Limit as u8,
            time_in_force: TimeInForce::Day as u16,
            price: Decimal::from_f64(price), quantity: Decimal::from_f64(qty),
            stop_price: Decimal::NULL,
        }
    }

    #[test]
    fn fill_to_exec_report() {
        use crate::codec::MessageBuffer;
        let mut book = OrderBook::new(42);
        book.submit(&make_order_for(1, 42, Side::Sell, 100.0, 10.0));
        let fills = book.submit(&make_order_for(2, 42, Side::Buy, 100.0, 10.0));

        let report = fills[0].to_exec_report();
        assert_eq!(report.order_id, 2);
        assert_eq!(report.instrument_id, 42);
        assert_eq!(report.exec_type(), Some(ExecType::Fill));
        assert!((report.last_px.to_f64() - 100.0).abs() < 1e-6);

        // Can encode as MGEP message
        let mut enc = MessageBuffer::with_capacity(256);
        enc.encode(0, 1, &report, None);
        let decoded: &ExecutionReportCore = MessageBuffer::decode(enc.as_slice());
        assert_eq!(decoded.order_id, 2);
    }

    #[test]
    fn multi_level_book() {
        let mut book = OrderBook::new(1);

        // Build a book
        for i in 0..5 {
            book.submit(&make_order(100 + i, Side::Buy, 95.0 + i as f64, 10.0));
            book.submit(&make_order(200 + i, Side::Sell, 101.0 + i as f64, 10.0));
        }

        assert_eq!(book.bid_levels(), 5);
        assert_eq!(book.ask_levels(), 5);
        assert!((book.best_bid().to_f64() - 99.0).abs() < 1e-6);
        assert!((book.best_ask().to_f64() - 101.0).abs() < 1e-6);
        assert_eq!(book.order_count(), 10);
    }
}
